import type { AgentManifest, Finding, SurfaceObject } from "../schemas/index.js";

export function renderMarkdownReport(manifest: AgentManifest): string {
  const counts = [
    ["Instructions", manifest.instructions.length],
    ["Skills", manifest.skills.length],
    ["Plugins", manifest.plugins.length],
    ["MCP servers", manifest.mcp_servers.length],
    ["Tools", manifest.tools.length],
    ["Secrets", manifest.secrets.length],
    ["RAG sources", manifest.rag_sources.length],
    ["Memory surfaces", manifest.memory.length],
    ["CI/CD", manifest.ci_cd.length]
  ];

  return [
    "# AgentCSP Report",
    "",
    "AgentCSP scanned this project as an agent security surface. Evidence snippets are redacted by default and secret values are not collected.",
    "",
    "## Scan Metadata",
    "",
    `- Root: \`${manifest.metadata.root_path}\``,
    `- Generated: \`${manifest.metadata.generated_at}\``,
    `- Manifest schema: \`${manifest.metadata.schema_version}\``,
    `- Secret values collected: \`${manifest.metadata.config.secret_values_collected}\``,
    `- Evidence redacted: \`${manifest.metadata.config.evidence_redacted}\``,
    "",
    "## Surface Inventory",
    "",
    ...counts.map(([label, count]) => `- ${label}: ${count}`),
    "",
    renderBlastRadius(manifest),
    "",
    renderFindings(manifest.findings),
    "",
    "## High-Risk Objects",
    "",
    renderObjectTable(manifest.static_blast_radius?.high_risk_objects ?? []),
    "",
    "## Notes",
    "",
    "- Policy actions in this MVP are recommended controls, not runtime enforcement decisions.",
    "- The Static Blast-Radius Summary is based on discovered files and normalized metadata, not live graph traversal.",
    "- Use `.agentcspignore` to exclude project-specific generated or sensitive paths."
  ].join("\n");
}

function renderBlastRadius(manifest: AgentManifest): string {
  const summary = manifest.static_blast_radius;
  if (!summary) return "## Static Blast-Radius Summary\n\nNo blast-radius summary was generated.";
  return [
    "## Static Blast-Radius Summary",
    "",
    `- Highest severity: \`${summary.highest_severity}\``,
    `- Read paths: ${summary.read_paths}`,
    `- Write paths: ${summary.write_paths}`,
    `- Execute paths: ${summary.execute_paths}`,
    `- External reach paths: ${summary.external_reach_paths}`,
    `- Secret reference paths: ${summary.secret_reference_paths}`,
    `- RAG surfaces: ${summary.rag_surfaces}`,
    `- Memory surfaces: ${summary.memory_surfaces}`,
    "",
    "### Recommended Controls",
    "",
    summary.recommended_controls.length > 0
      ? summary.recommended_controls.map((control) => `- ${control}`).join("\n")
      : "- No recommended controls were generated."
  ].join("\n");
}

function renderFindings(findings: Finding[]): string {
  if (findings.length === 0) {
    return "## Findings\n\nNo findings were generated by the enabled rule pack.";
  }

  return [
    "## Findings",
    "",
    "| Severity | Rule | Object | Recommended control | Risk factors |",
    "| --- | --- | --- | --- | --- |",
    ...findings.map((finding) => {
      const factors = finding.risk.rationale.length > 0 ? finding.risk.rationale.join("; ") : "baseline rule match";
      return `| ${finding.severity} | ${finding.rule_id} | \`${finding.matched_object.type}:${finding.matched_object.name}\` | ${finding.recommended_control.replaceAll("_", " ")} | ${escapeTable(factors)} |`;
    })
  ].join("\n");
}

function renderObjectTable(objects: SurfaceObject[]): string {
  if (objects.length === 0) return "No high-risk objects were identified.";
  return [
    "| Type | Name | Path | Authority |",
    "| --- | --- | --- | --- |",
    ...objects.map((object) => `| ${object.type} | ${escapeTable(object.name)} | \`${object.path}\` | ${object.actions.join(", ") || "read"} |`)
  ].join("\n");
}

function escapeTable(value: string): string {
  return value.replaceAll("|", "\\|");
}
